version: '2'

services:
    webserver:
     restart: always
     container_name: best_web
     image: kyma/docker-nginx
     command: nginx
     volumes:
      - ../src:/var/www
     working_dir: /var/www
     ports:
      - "8030:80"
